### ISSUE TITLE
2 Indicators selecten

### ISSUE THREAD

**Issue by NickLammerskitten** [simonkrempin/geo_heat#11]
Es sollen 2 Indicators ausgewählt werden. Über die Darstellung müssen wir dann diskutieren. 
Die Graphen, in denen wir den Zusammenhang zwischen den Daten soll in einem anderen Issue thematisiert werden

**Comment by simonkrempin** [comment]
daran denken, die Metadaten noch richtig zu berechnen

**Comment by simonkrempin** [comment]
Komischer Map / Datendarstellungs glitch fixen

**Comment by simonkrempin** [comment]
same key?
