### ISSUE TITLE
Create Legend in bottom right corner

### ISSUE THREAD

**Issue by Jaybee18** [simonkrempin/geo_heat#22]
Just take the .rgbAt() value at 0%, 25%, 50%, 75% and 100% (so 0.0, 0.25, 0.5, 0.75 and 1.0).

![image](https://github.com/user-attachments/assets/034b6598-b8b0-452a-8328-6a273ee6fff3)

**Comment by Jaybee18** [comment]
- [ ] Legende sollte sich den Werten des aktuell angezeigten indicators anpassen.

- [ ] Und im Moment wird die Legende angezeigt, wenn man die line charts öffnet, das sollte so nicht sein.

**Comment by simonkrempin** [comment]
hier bitte noch die Ecken rund machen
