### ISSUE TITLE
csv parser to json

### ISSUE THREAD

**Issue by simonkrempin** [simonkrempin/geo_heat#3]
to improve the process of adding data to the map

**Comment by simonkrempin** [comment]
Wir müssen noch ein paar Werte rausnehmen, weil es entweder keine Länder sind oder weil wir die Länder nicht darstellen (oder lassen wir die einfach drinnen)
![image](https://github.com/simonkrempin/geo_heat/assets/67335158/ffe8b2ad-81c9-4ba8-bf6e-d989bdc8b605)

**Comment by Jaybee18** [comment]
ich glaube dir können wir ignorieren, weil die map view die eh nicht findet
(wäre aber auch nicht schwer, die zu entfernen, wenn das nötig sein sollte)

**Comment by simonkrempin** [comment]
Die werden aber im Grid dargestellt. Also sollten wir mindestens nicht Länder rausnehmen

**Comment by Jaybee18** [comment]
habe gerade auch gesehen, ich nehme die raus
