### ISSUE TITLE
Verdacht: die niedrigsten Werte werden nicht richtig dargestellt

### ISSUE THREAD

**Issue by simonkrempin** [simonkrempin/geo_heat#42]
Ich vermute, dass die niedrigsten Werte nicht ganz richtig dargestellt werden.
![image](https://github.com/user-attachments/assets/d8dd3894-3691-40b6-ae54-5d83df237aa4)
In meinem Kopf müssten die Länder nämlich eine hellere Darstellung haben

**Comment by NickLammerskitten** [comment]
Ja richtig, hatte ich auch schon angemerkt. Wenn Werte viele Nachkommastellen haben, werden die dunkler dargestellt. Kannst du einmal die Indicator die du auf dem Bild ausgewählt hast dazuschreiben? Damit man das reproduzieren kann.

**Comment by simonkrempin** [comment]
@NickLammerskitten das hat keinen Zusammenhang zu #41, ich meine was anderes damit.
